### ISSUE TITLE
Push a new release for 10.1

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DBM-Shadowlands#4]
Hi @MysticalOS, 

Was the intention to push a new release of this module for 10.1? I noticed you made the toc changes and added the icons, but the release was never tagged. I only ask as this is the only DBM package that didn't get a 10.1 release.

Pardon for being 'that guy', but I figured there's a maybe a 5% chance that this just flew under your radar, so I thought I'd check.

**Comment by MysticalOS** [comment]
i'm well aware of it just haven't gotten around to it yet
